<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="Sts2ApiCompat;Sts2DataDir">
    <PropertyGroup>
        <RitsuLibSharedModule>true</RitsuLibSharedModule>
        <AssemblyName>STS2-RitsuLib.Ui</AssemblyName>
    </PropertyGroup>
    <Import Project="..\..\build\RitsuLib.Module.props"/>
    <Import Project="..\..\build\RitsuLib.Modules.items"/>
    <ItemGroup>
        <Compile Include="@(RitsuLibUiSource)" Link="Ui\%(RecursiveDir)%(Filename)%(Extension)"/>
        <ProjectReference Include="..\shared\STS2-RitsuLib.Shared.csproj"/>
        <Using Include="STS2RitsuLib.RitsuModuleRuntime" Alias="RitsuLibFramework"/>
        <Using Include="STS2RitsuLib.Shared"/>
    </ItemGroup>
</Project>
